name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-bot:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
#         this is important https://github.com/actions/checkout/issues/261#issuecomment-825419286
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
#       - name: Set up Homebrew
#         id: set-up-homebrew
#         uses: Homebrew/actions/setup-homebrew@master

      - name: Install Homebrew Bundler RubyGems
        run: brew install-bundler-gems

      - run: brew test-bot --only-cleanup-before

#     Hack for now, this file is getting created with the output "All Steps Succeeded".
#     Homebrew doesn't like this because its an uncommitted file, so it fails the build.
      - run: rm steps_output.txt
#     also a hack, for some reason homebrew is not setting the default homebrew url correctly.
#     There seems to have been a recent breaking change in homebrew, hopefully this doesn't have to
#     live here for long.
#       - run: git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core
#       - run: brew tap Homebrew/core
#       - run: brew tap Homebrew/cask

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax
      
      - run: |
          git status
          git log -n 1
        shell: bash

      - run: brew test-bot --only-formulae --debug
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: '*.bottle.*'
