name: brew test-bot
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/Cargo.toml"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/Cargo.toml"
jobs:
  test-bot:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - name: Get latest release for momento-cli
        if: |
          github.event_name == 'pull_request' &&
          matrix.os == 'macos-latest'
        uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: momentohq
          repo: momento-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download archive files
        if: |
          github.event_name == 'pull_request' &&
          matrix.os == 'macos-latest'
        run: |
          echo "VERSION=$(echo -n ${{ fromJSON(steps.get_latest_release.outputs.data).name }} | tail -c 6)" >> $GITHUB_ENV
          ARCHIVE=archive-${{ env.VERSION }}.tar.gz
          LOCATION=https://github.com/momentohq/momento-cli/releases/download/v.${{ env.VERSION }}/$ARCHIVE
          echo $LOCATION
          curl -OL $LOCATION
          tar -zxvf $ARCHIVE
          pushd archive-${{ env.VERSION }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          override: true

      - name: Build aarch64
        if: |
          github.event_name == 'pull_request' &&
          matrix.os == 'macos-latest'
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target aarch64-apple-darwin

      - name: Build tar.gz for arm_big_sur
        if: |
          github.event_name == 'pull_request' &&
          matrix.os == 'macos-latest'
        run: |
          tar zcvf momento-cli${{ env.VERSION }}.arm_big_sur.bottle.tar.gz ./target/aarch64-apple-darwin/release
          popd

      - run: brew test-bot --only-formulae
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: "*.bottle.*"
